name: ACR scan
on:
  push:
    branches: [ main ]
jobs:
  acr-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Run ACR scan
      uses: azure/container-scan@v0.1.0
      with:
        registry: containerscandemo.azurecr.io
        image: tipsandtrickscontainer:tipsandtrickscontainer:latest
        severity: 'High'
        fail-on: 'High'
        token: ${{ secrets.AZURE_CREDENTIALS }}       

